### ISSUE TITLE
build template for godot 2.1.5 include arm 64

### ISSUE THREAD

**Issue by SMaiLubis** [Shin-NiL/godot-custom-mobile-template#2]
can i ask build template for godot 2.1.5 include arm 64?
my app is get warning from google
![google warning 64nit](https://user-images.githubusercontent.com/46646098/57183054-66ed4200-6ee2-11e9-83b0-32430a836b2d.png)

**Comment by Shin-NiL** [comment]
Fair enough, I'll do that ASAP.

**Comment by Shin-NiL** [comment]
Done.
