### ISSUE TITLE
Android Template Godot 3.1.1 android_release.apk is not working

### ISSUE THREAD

**Issue by cemcem7** [Shin-NiL/godot-custom-mobile-template#3]
everything is fine and working when im exporting a debug version but when i export the release version with android_release.apk my exported project is crashing at the start.I even tried to export a release version with android_debug.apk and it worked fine.

**Comment by Shin-NiL** [comment]
I have no idea, just tested here with release and worked fine. Try to debug with ```adb logcat -s godot```

**Comment by cemcem7** [comment]
Thank you for your answer.I started to learn godot just 8 days ago so i dont understand what you are saying with "debug with adb logcat -s godot" and there is somebody else also having the same problem with me [https://godotengine.org/qa/43777/godot-release-version-crashes-opening-debug-version-works?show=43777#q43777](url) also im using both admob and share modules.
Thank you for your answer

**Comment by burstina** [comment]
I have no problem witn 3.1.1. My app uses vibration and shafe and worksfine on different Android devices.

**Comment by Shin-NiL** [comment]
My bad, adb is a command line tool from[ Android SDK](https://developer.android.com/studio/#command-tools), with it you'll be able to debug your game. Can you build and run a smaller 'hello world' project with the release template?

**Comment by cemcem7** [comment]
I did build a "hello world" project and it worked, but still my game with the release template is not working. Why is that am i using a module that is not supported in the android_release.apk ? or why the release template is smaller than the debug one ?

**Comment by Shin-NiL** [comment]
The release template is smaller because it excludes all the additional debug contents, so it's expected. 
Which modules are you using?

**Comment by cemcem7** [comment]
Share module with the admob module.I did manage to compile a release and a debug apk with your docs and still only the debug one is working.

**Comment by Shin-NiL** [comment]
You should try to debug with adb so.

**Comment by cemcem7** [comment]
`* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
E/godot   (13614): **WARNING**: Couldn't get executable path from /proc/self/exe, using argv[0]
E/godot   (13614):    At: drivers\unix\os_unix.cpp:514:get_executable_path() - Couldn't get executable path from /proc/self/exe, using argv[0]
I/godot   (13614): Loading Android module: org/godotengine/godot/GodotAdMob
I/godot   (13614): Loading Android module: org/godotengine/godot/GodotShare
I/godot   (13614): OpenGL ES 2.0 Renderer: Adreno (TM) 330
E/godot   (13614): **WARNING**: Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
E/godot   (13614):    At: scene\main\scene_tree.cpp:1158:_update_root_rect() - Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
E/godot   (13614): **WARNING**: Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
E/godot   (13614):    At: scene\main\scene_tree.cpp:1241:_update_root_rect() - Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
E/godot   (14163): **WARNING**: Couldn't get executable path from /proc/self/exe, using argv[0]
E/godot   (14163):    At: drivers\unix\os_unix.cpp:514:get_executable_path() - Couldn't get executable path from /proc/self/exe, using argv[0]
I/godot   (14163): Loading Android module: org/godotengine/godot/GodotAdMob
I/godot   (14163): Loading Android module: org/godotengine/godot/GodotShare
I/godot   (14163): OpenGL ES 2.0 Renderer: Adreno (TM) 330
E/godot   (14163): **WARNING**: Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
E/godot   (14163):    At: scene\main\scene_tree.cpp:1158:_update_root_rect() - Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
E/godot   (14163): **WARNING**: Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
E/godot   (14163):    At: scene\main\scene_tree.cpp:1241:_update_root_rect() - Font oversampling does not work in 'Viewport' stretch mode, only '2D'.`

Force finishing activity com.my.game/org.godotengine.godot.Godot
Process com.my.game (pid 15547) (adj 15) has died.

**Comment by cemcem7** [comment]
After fixing the strect mode warning ;

E/godot   (23949): **WARNING**: Couldn't get executable path from /proc/self/exe, using argv[0]
E/godot   (23949):    At: drivers\unix\os_unix.cpp:514:get_executable_path() - Couldn't get executable path from /proc/self/exe, using argv[0]
I/godot   (23949): Loading Android module: org/godotengine/godot/GodotAdMob
I/godot   (23949): Loading Android module: org/godotengine/godot/GodotShare
I/godot   (23949): OpenGL ES 2.0 Renderer: Adreno (TM) 330
W/ActivityManager(  860): mDVFSHelper.release()
W/ActivityManager(  860):   Force finishing activity com.my.game/org.godotengine.godot.Godot
W/ActivityManager(  860): mDVFSHelper.acquire()
W/ActivityManager(  860): mDVFSHelper.release()
I/ActivityManager(  860): Process com.my.game (pid 23949) (adj 13) has died.

**Comment by cemcem7** [comment]
W/ActivityManager(  860):   Force finishing activity com.my.game/org.godotengine.godot.Godot
W/ActivityManager(  860): Exception thrown during pause
W/ActivityManager(  860): android.os.DeadObjectException
W/ActivityManager(  860):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  860):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:701)
W/ActivityManager(  860):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1063)
W/ActivityManager(  860):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3301)
W/ActivityManager(  860):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3135)
W/ActivityManager(  860):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:3388)
W/ActivityManager(  860):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11799)
W/ActivityManager(  860):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11670)
W/ActivityManager(  860):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12361)
W/ActivityManager(  860):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11904)
W/ActivityManager(  860):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
W/ActivityManager(  860): mDVFSHelper.acquire()
W/ActivityManager(  860): Failed setting oom adj of ProcessRecord{43f538d0 576:com.my.game/u0a572} to 1
I/ActivityManager(  860): Process com.my.game (pid 576) (adj 0) has died.

**Comment by Shin-NiL** [comment]
I couldn't identify anything related to the modules, maybe this issue is from the engine not the modules. One thing we can try to do is make sure that it is the case. 

Could you remove the calls from the modules from your project (maybe just the ones in project.godot could be enough) and try to use the official templates?

**Comment by cemcem7** [comment]
Tried to remove calls one by one and it still crashes.I think its abouth the engine is well because i did remove the both calls from the modules and it still crashed.

**Comment by cemcem7** [comment]
would it be a problem if i release the game on play store build with android_debug.apk and singed with release.keystore ?

**Comment by Shin-NiL** [comment]
Never tried to do that, I really don't know. Maybe Google won't allow that, but it's just a guess. Have you tried to talk or open an issue at the Godot repository? Maybe somebody can help.

**Comment by cemcem7** [comment]
Well, thank you, i did post it on the godot engine Q&A and if i come up with a solution i will post it here is well. Again thank you for your help

**Comment by cemcem7** [comment]
I did solve the issue, in the start screen i was using hideBanner() fucntion without showing one, its not crashing the game on the debug version but it crashes instantly on the release version without an error.
