### ISSUE TITLE
I don't know how to write you a message.

### ISSUE THREAD

**Issue by GhostWalker562** [Shin-NiL/godot-custom-mobile-template#5]
Anyways I gotchu with an iOS template, I made the repository based off this README.md but the template works for me at least. I made it using GoogleAdMob Sdk 7.46 so there's a bit more the user will probably have to do but it works :D. I only have arm64 and arm only for release, so no debug and 86 for both rn. https://github.com/GhostWalker562/godot-admob-iOS-precompiled. Thanks to you for everything though!
Btw idk how to message you so I'm just doing this.

**Comment by Shin-NiL** [comment]
Thank you very much!
I'll update my readme file linking your repository.

**Comment by Shin-NiL** [comment]
Done!
