### ISSUE TITLE
iOS compiled custom template

### ISSUE THREAD

**Issue by mani144** [Shin-NiL/godot-custom-mobile-template#7]
Greetings,

I would like to put the compiled template for iOS with your template,
can you please share the parameters for the compiled version for android ?

**Comment by Shin-NiL** [comment]
Well, I'm using the default building parameters. Nothing special I think.

**Comment by mani144** [comment]
> Well, I'm using the default building parameters. Nothing special I think.

the default android modules makes the app size 40+ mb , if you can share what modules did you disabled for i can try it on mac and build an ios template for admob , share ,and vibration

**Comment by Shin-NiL** [comment]
As I don't know wich features the final user will need, I didn't disable anything.

**Comment by mani144** [comment]
Oh , okay
the size of iphone template around 140 do you think i should upload it ?
Thanks anyway.

**Comment by mani144** [comment]
> As I don't know wich features the final user will need, I didn't disable anything.

i used the same thing documented here :
https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html

scons platform=android target=release_debug android_arch=armv7
scons platform=android target=release_debug android_arch=arm64v8

and im getting a size around 20+ mb without any custom modules

**Comment by mani144** [comment]
@Shin-NiL did you create x64 and 32 version ? 
or just 64 ?

**Comment by Shin-NiL** [comment]
For Android I'm compiling for armv7, arm64v8, x86 and x86_64.
