### ISSUE TITLE
New compile versions

### ISSUE THREAD

**Issue by ferhand** [Shin-NiL/godot-custom-mobile-template#9]
Would be nice if you could compile this for the version Godot 3.2

**Comment by Shin-NiL** [comment]
Sorry, I have no plans to compile this module anymore as I'm using the new plugin system right now. For Admob, for example, try to use [this module](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin).

**Comment by nikhilCad** [comment]
@ferhand did you compile it?
